### ISSUE TITLE
Use array 'at' method instead of array 'filter' method

### ISSUE THREAD

**Issue by maeema** [aemkei/jsfuck#125] opened 2022-07-19 12:31 UTC
While Internet Explorer is now dead, and the 'at' method is compatible with all other browsers, I think using the 'at' to eval the code can reduce the size of the compilation results a little bit.

that means:
 * Function =>  `[]["at"]` instead of `[]["filter"]`.
 * eval => `[]["at"]["constructor"]( CODE )()` instead of `[]["filter"]["constructor"]( CODE )()`.
 * window => `[]["at"]["constructor"]("return this")()` instead of `[]["filter"]["constructor"]("return this")()`

**Comment by hazzik** [comment] 2022-07-19 22:35
Duplicate of #119

**Comment by hazzik** [comment] 2022-07-19 22:35
Also, it is not 'filter' anymore it is 'flat'

**Closed** 2022-07-19 23:25 UTC

**Comment by maeema** [comment] 2022-07-19 23:26
The discussion will continue on #119.
